name: CI Order Service
on:
  push:
    branches: [ master, feature/gateway ]
    paths:
      - 'gateway/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'gateway/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build Order Service
        working-directory: gateway
        run: mvn clean install